<a href="https://colab.research.google.com/github/Jczo/MyMLRepo/blob/master/Jose_Canalizo911EmergencyCalls.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Case Study

Congrats! You have been contracted to conduct a brief analysis of a dataset containing ememrgency calls in order to determine the allocation of funds to you local authorities.  This analysis will play a role in deciding changes to the emergency response department.

The data is based in 911 emergency calls and your job is to determine a variety of issues regarding said calls.

1. Using Pandas and Numpy, analyse the data and come up with 5 questions that you would like to answer about the data.

2. the instructor will provide a rnage of questions to answer and you should use your knowledge to complte them as a team.

The 5 questions:
- ***How many unique titles are there? (call reasons)***
 - 110 unique titles
- ***What are the top 5 reasons for calling 911?***
The top 5 reasons are:

  - Traffic: VEHICLE ACCIDENT - 23.18%

  - Traffic: DISABLED VEHICLE - 7.74%

  - Fire: FIRE ALARM - 5.52%

  - EMS: RESPIRATORY EMERGENCY - 5.14%

  - EMS: CARDIAC EMERGENCY - 5.04%

- ***How many calls are vehicle related?***
  - Vehicle related calls are 37.78% of all calls

- ***which zip code had the highest calls? Which had the least?***
  - 19401 had the most amount of calls
  - 17752 had the least amount of calls

- ***Which day had the most calls? Which day had the least?***
  - 2015-12-10 had the most calls, with 0.008041% of all calls.
  - 2016-07-10 had the least amount of calls, with 0.001005 of all calls

In [1]:
import pandas as pd
import numpy as np


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
data = pd.read_csv('/content/drive/MyDrive/911data/911.csv')

In [4]:
data.head()

lat        lng  ...                        addr  e
0  40.297876 -75.581294  ...      REINDEER CT & DEAD END  1
1  40.258061 -75.264680  ...  BRIAR PATH & WHITEMARSH LN  1
2  40.121182 -75.351975  ...                    HAWS AVE  1
3  40.116153 -75.343513  ...          AIRY ST & SWEDE ST  1
4  40.251492 -75.603350  ...    CHERRYWOOD CT & DEAD END  1

[5 rows x 9 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99492 entries, 0 to 99491
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   lat        99492 non-null  float64
 1   lng        99492 non-null  float64
 2   desc       99492 non-null  object 
 3   zip        86637 non-null  float64
 4   title      99492 non-null  object 
 5   timeStamp  99492 non-null  object 
 6   twp        99449 non-null  object 
 7   addr       98973 non-null  object 
 8   e          99492 non-null  int64  
dtypes: float64(3), int64(1), object(5)
memory usage: 6.8+ MB


**1. How many unique titles are there?**

In [6]:
uniqueTitles = data['title'].unique()
titlesCount = uniqueTitles.size
print(uniqueTitles)


['EMS: BACK PAINS/INJURY' 'EMS: DIABETIC EMERGENCY' 'Fire: GAS-ODOR/LEAK'
 'EMS: CARDIAC EMERGENCY' 'EMS: DIZZINESS' 'EMS: HEAD INJURY'
 'EMS: NAUSEA/VOMITING' 'EMS: RESPIRATORY EMERGENCY'
 'EMS: SYNCOPAL EPISODE' 'Traffic: VEHICLE ACCIDENT -'
 'EMS: VEHICLE ACCIDENT' 'Traffic: DISABLED VEHICLE -'
 'Fire: APPLIANCE FIRE' 'EMS: GENERAL WEAKNESS'
 'Fire: CARBON MONOXIDE DETECTOR' 'EMS: UNKNOWN MEDICAL EMERGENCY'
 'EMS: UNRESPONSIVE SUBJECT' 'Fire: VEHICLE ACCIDENT'
 'EMS: ALTERED MENTAL STATUS' 'Fire: FIRE ALARM' 'EMS: CVA/STROKE'
 'Traffic: ROAD OBSTRUCTION -' 'EMS: SUBJECT IN PAIN' 'EMS: HEMORRHAGING'
 'EMS: FALL VICTIM' 'EMS: ASSAULT VICTIM' 'EMS: SEIZURES'
 'EMS: MEDICAL ALERT ALARM' 'EMS: ABDOMINAL PAINS' 'Fire: PUMP DETAIL'
 'Fire: FIRE INVESTIGATION' 'EMS: OVERDOSE' 'EMS: MATERNITY'
 'EMS: UNCONSCIOUS SUBJECT' 'EMS: CHOKING' 'EMS: LACERATIONS'
 'Fire: TRASH/DUMPSTER FIRE' 'Fire: UNKNOWN TYPE FIRE'
 'Fire: BUILDING FIRE' 'Fire: ELECTRICAL FIRE OUTSIDE'
 'Fire: DEBRIS/FLUIDS ON HIGH

In [7]:
print(titlesCount)

110


There are 110 unique titles for the 911 calls.

What are the top 5 reasons for calling 911?

In [8]:
data['title'].value_counts(normalize = True).head(5) * 100

Traffic: VEHICLE ACCIDENT -    23.183774
Traffic: DISABLED VEHICLE -     7.741326
Fire: FIRE ALARM                5.524062
EMS: RESPIRATORY EMERGENCY      5.138102
EMS: CARDIAC EMERGENCY          5.037591
Name: title, dtype: float64

The top 5 reasons are:

Traffic: VEHICLE ACCIDENT -    23.18%

Traffic: DISABLED VEHICLE -     7.74%

Fire: FIRE ALARM -              5.52%

EMS: RESPIRATORY EMERGENCY -    5.14%

EMS: CARDIAC EMERGENCY -        5.04%


How many calls are vehicle related?

In [9]:
boolean_mask = data['title'].str.lower().str.contains('vehicle')
data[boolean_mask]['title'].unique()

array(['Traffic: VEHICLE ACCIDENT -', 'EMS: VEHICLE ACCIDENT',
       'Traffic: DISABLED VEHICLE -', 'Fire: VEHICLE ACCIDENT',
       'Traffic: VEHICLE LEAKING FUEL -', 'Fire: VEHICLE FIRE',
       'Traffic: VEHICLE FIRE -', 'Fire: VEHICLE LEAKING FUEL',
       'EMS: VEHICLE FIRE', 'EMS: DISABLED VEHICLE'], dtype=object)

In [11]:
round(data[boolean_mask]['title'].count()/len(data) * 100,2)

37.78

***Vehicle related calls*** are 37.78% of all calls

which zip code had the highest calls? Which had the least?

In [12]:
data['zip'].value_counts(normalize = True).head(1) * 100 #HEAD(1)

19401.0    8.05545
Name: zip, dtype: float64

- 19401 had the most amount of calls
- 17752 had the least amount of calls


In [13]:
data['zip'].value_counts(normalize = True).tail(1) * 100 #Tail(1)

17752.0    0.001154
Name: zip, dtype: float64

Which day had the most calls? Which day had the least?

In [15]:
data['timeStamp'].value_counts(normalize = True).head(1) * 100

2015-12-10 17:40:01    0.008041
Name: timeStamp, dtype: float64

In [17]:
data['timeStamp'].value_counts(normalize = True).tail(1) * 100

2016-07-10 12:17:00    0.001005
Name: timeStamp, dtype: float64

- 2015-12-10 had the most calls, with 0.008041% of all calls.

- 2016-07-10 had the least amount of calls, with 0.001005 of all calls